//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCRUD {
	
	
	public partial class indexPage {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.HiddenField idproduto;
		
		protected System.Web.UI.WebControls.TextBox txtnome;
		
		protected System.Web.UI.WebControls.TextBox txtdescricao;
		
		protected System.Web.UI.WebControls.TextBox txtvalor;
		
		protected System.Web.UI.WebControls.TextBox txtquantidade;
		
		protected System.Web.UI.WebControls.Button btnsalvar;
		
		protected System.Web.UI.WebControls.Button btneditar;
		
		protected System.Web.UI.WebControls.Button btndeletar;
		
		protected System.Web.UI.WebControls.Label lblmensagemok;
		
		protected System.Web.UI.WebControls.Label lblmensagemerro;
	}
}
